In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df=sns.load_dataset('iris')

In [5]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [7]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x=df.drop('species',axis=1)
y=df['species']

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [17]:
model_knn=KNeighborsClassifier(n_neighbors=13)

In [18]:
model_knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [19]:
model_knn.score(x_test,y_test)

1.0

In [20]:
from sklearn.svm import SVC

In [27]:
model_svm=SVC(gamma='auto')

In [28]:
model_svm.fit(x_train,y_train)

SVC(gamma='auto')

In [29]:
model_svm.score(x_test,y_test)

1.0

In [30]:
#Grid Search Cv
from sklearn.model_selection import GridSearchCV

In [31]:
classifier=GridSearchCV(model_svm,{'C':[1,18,20,30],'kernel':['rbf','linear']},cv=5,return_train_score=False)

In [32]:
classifier.fit(x,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 18, 20, 30], 'kernel': ['rbf', 'linear']})

In [33]:
classifier.cv_results_

{'mean_fit_time': array([0.00504375, 0.00431561, 0.00492287, 0.0040596 , 0.0041049 ,
        0.00385337, 0.00418935, 0.00389071]),
 'std_fit_time': array([5.50999666e-04, 3.69421753e-04, 1.32874346e-03, 4.27226120e-04,
        6.35807236e-05, 3.04523322e-04, 1.12182020e-04, 1.11969386e-04]),
 'mean_score_time': array([0.00375476, 0.00383334, 0.00324354, 0.00355825, 0.00306611,
        0.00322022, 0.00308557, 0.00283813]),
 'std_score_time': array([8.37409283e-04, 1.38159789e-03, 1.25780803e-04, 6.63274567e-04,
        7.14537578e-05, 6.11303686e-04, 8.81739341e-05, 2.24478556e-04]),
 'param_C': masked_array(data=[1, 1, 18, 18, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 18, 'kernel': 'rbf'},
  {'C': 18, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.93333333, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.97333333, 0.96666667, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.02494438, 0.0421637 , 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 3, 5, 4, 5, 7, 7], dtype=int32)}

In [34]:
results=pd.DataFrame(classifier.cv_results_)

In [35]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005044,0.000551,0.003755,0.000837,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.004316,0.000369,0.003833,0.001382,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.004923,0.001329,0.003244,0.000126,18,rbf,"{'C': 18, 'kernel': 'rbf'}",0.966667,1.0,0.933333,0.966667,1.0,0.973333,0.024944,3
3,0.004060,0.000427,0.003558,0.000663,18,linear,"{'C': 18, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,5
4,0.004105,0.000064,0.003066,0.000071,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,4
5,0.003853,0.000305,0.003220,0.000611,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,5
6,0.004189,0.000112,0.003086,0.000088,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.003891,0.000112,0.002838,0.000224,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [36]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       18          rbf         0.973333
3       18       linear         0.966667
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000